const styles = {
    black: [
        'table#tablaCasos thead tr th,section.content .card .body,.theme-red .sidebar .legal {background: black !important;color: white;}',
        'section.content.card.header.bg-indigo,.theme-red.navbar,.theme-red.sidebar.menu.list.ml-menu {background: black!important;}',
        'body,.theme-red.sidebar.menu.list.toggled,.sidebar {background: black;}',
        '.table-striped>tbody>tr:nth-of-type(odd){color: black;background-color: white;font-weight: bolder;font-size: 1.5rem;}',
        '.table-striped>tbody>tr:nth-of-type(even) {background-color: #040404;}',
        'ul.list li:not(first) > a i,ul.list li:not(first) > a span,ul.list li:not(first) > a {color: white!important;}',
        '.modal-content.modal-col-blue,.modal-content.modal-col-black,.modal-content.modal-col-cyan,.modal-content.modal-col-light-blue,.modal-content.modal-col-teal {background-color: black;}',
        '.modal-content.modal-col-blue > form input, .modal-content.modal-col-blue > form select,.modal-content.modal-col-black > form input, .modal-content.modal-col-black > form select,.modal-content.modal-col-cyan > form input, .modal-content.modal-col-cyan > form select.modal-content.modal-col-light-blue > form input, .modal-content.modal-col-light-blue > form select,.modal-content.modal-col-teal > form input, .modal-content.modal-col-teal > form select {background-color: black!important;color: white;border-bottom-style: groove;}',
        '#div_ajax_tabla_file_subidos table.table.table.bg-blue {background-color: black!important;}',
        '.navbar-nav > li > .dropdown-menu {background-color: #212121;color: white;font-size: larger;}',
        '.page-loader-wrapper {  background: #000 !important;}',
    ],
    moradoDark: [
        'body.theme-default{overflow:hidden}',
        '.modal-col-blue,.modal-content.modal-col-black,.modal-col-cyan,.modal-col-light-blue,.modal-col-teal{background-color:#161616!important;color:#fff}',
        'tr.template-download.fade.in{border-bottom:solid 1px #fff}',
        'tr.even{background-color:#314151!important;color:#fff}',
        'tr.odd{background-color:#000!important;color:#fff}',
        '.menu{background:#000;color:#fff}',
        '.panel-body>div tbody tr:hover,select#s_data_to{color:#000}',
        '#accordion_9>div a,#collapseOne_1>* div,._box h3,._sub{color:#fff}',
        '.contenido_extension_agendados,.main_box li.body{background:#000}',
        '.panel-default>.panel-heading{color:#000!important}',
        '.login-page .login-box .msg,.login-page .login-box>div span i{color:#fff!important}',
        'a.waves-effect.waves-block>*,ul.ml-menu>li a{color:#fff!important}',
        '.navbar-header a{text-decoration:none}',
        'div#collapseOne_1.panel-collapse.collapsing,div#collapseOne_1.panel-collapse.in{overflow:auto!important;height:37rem!important}',
        'a.list-group-item:focus,a.list-group-item:hover,button.list-group-item:focus,button.list-group-item:hover{background-color:transparent!important}',
        '#form1 .form-group .panel-body.overflow-panel,#form1 .outer_div .panel-body.overflow-panel{overflow:hidden!important;background-color:transparent!important}',
        '#form1 .outer_div>.panel-heading{background-color:transparent!important}', 'a.list-group-item{padding:.5rem;margin-bottom:0!important;background-color:unset;border:unset}',
        '.login-box>.card .footer .status{background-color:#5a4585;color:#fff}',
        '.pagination>li.active a,.pagination>li.next a,.pagination>li.previous a{background:#38024fe0!important;color:#fff!important}',
        '.menu>div li.header{background-color: #541bc1 !important;}',
        '.list-group-item:nth-child(odd)>.row{background: #6c33b7 !important;}',
        '.outer_div_telefono .overflow-panel{height: 70rem !important;overflow: auto !important;}',
        '.outer_div_telefono>div a .row h3,a.list-group-item,a.list-group-item:hover,button.list-group-item,button.list-group-item:hover{color: white !important;}',
        '.list-group-item:nth-child(even)>.row{background: black;color: white;}',
        'a.toggled.waves-effect,a.waves-effect.waves-block:hover,a.waves-effect.waves-block:hover>*{color: rgb(117, 60, 255) !important;}',
        '.panel{border-color: #8d00e5 !important;background-color: black !important;color: white;}',
        '.panel.panel-primary{padding: 1rem;}',
        '.panel>.panel-heading{color: #fff;background-color: #6c33b7;border-color: #6c33b7;}',
        '.theme-deep-orange .navbar{background-color: #48268d;}',
        'body.theme-red{height: 100vh;background-position: center;}',
        'aside#leftsidebar{background: transparent;}',
        '.menu{background: transparent;}',
        '::-webkit-scrollbar{width: 9px;background: #6c33b7;}',
        '::-webkit-scrollbar-thumb{background: black;border-radius: 1rem;}',
        '.outer_div .panel-success>.panel-heading{filter: invert(1);}',
        '.outer_div .panel-success>.panel-heading h2.panel-title{background-color: chartreuse !important;color: black !important;}',
        '.btn-consultar-deuda{border-color: #70ff03 !important;color: black !important;font-size: 1.5rem;}',
        '.list-group .list-group-bg-grey,.list-group .list-group-bg-grey:hover{background-color: #2c0755 !important;}',
        'div#div_ajax_busca_tickets>div .panel.panel-primary .panel-title{background: #462f76 !important;}',
        'div#div_ajax_busca_tickets>div a{color: white;}',
        'li.list-group-item{background: black;}',
        'li.list-group-item.list-group-bg-light-blue{background-color: #401a91;}',
        'body.theme-default {  overflow: hidden;}',
        'body.theme-default nav.navbar {  background-color: black;}',
        'body.theme-default section .menu {  background-color: black;}',
        'body.theme-default section .menu ul > li ~ li {  color: white;}',
        'body.theme-default section .menu ul > li ~ li:hover {  color: #a84cfd !important;}',
        '.page-loader-wrapper {  background: #000 !important;}',
        '.page-loader-wrapper p {  color: white !important;}',
        'body {  background-color: #000000 !important;  color: white;}',
        '.modal-col-blue,.modal-content.modal-col-black,.modal-col-cyan,.modal-col-light-blue,.modal-col-teal{  background-color: #161616 !important;  color: white;}',
        'tr.template-download.fade.in {  border-bottom: solid 1px white;}',
        'tr.even {  background-color: #314151 !important;  color: white;}',
        'tr.odd {  background-color: black !important;  color: white;}',
        '.menu {  background: black;  color: white;}',
        'select#s_data_to,.panel-body > div tbody tr:hover {  color: black;}',
        '._sub,._box h3,#accordion_9 > div a,#collapseOne_1 > * div {  color: white;}',
        '.main_box li.body,.contenido_extension_agendados {  background: black;}',
        '.panel-default > .panel-heading {  color: black !important;}',
        '.login-page .login-box .msg,.login-page .login-box > div span i {  color: white !important;}',
        'ul.ml-menu > li a,a.waves-effect.waves-block > * {  color: white !important;}',
        '.navbar-header a { text-decoration: none;}',
        'div#collapseOne_1.panel-collapse.in,div#collapseOne_1.panel-collapse.collapsing {  overflow: auto !important;  height: 37rem !important;}',
        'a.list-group-item:hover,button.list-group-item:hover,a.list-group-item:focus,button.list-group-item:focus {  background-color: transparent !important;}',
        '#form1 .form-group .panel-body.overflow-panel,#form1 .outer_div .panel-body.overflow-panel {  overflow: hidden !important;  background-color: transparent !important;}',
        '#form1 .outer_div > .panel-heading {  background-color: transparent !important;}',
        'a.list-group-item {  padding: 0.5rem;  margin-bottom: 0 !important;  background-color: unset;  border: unset;}',
        '.login-box > .card .footer .status {  background-color: #5a4585;  color: white;}',
        '.pagination > li.active a,.pagination > li.previous a,.pagination > li.next a {  background: #38024fe0 !important;  color: white !important;}',
        "a.toggled.waves-effect, a.waves-effect.waves-block:hover, a.waves-effect.waves-block:hover > *,.spinner-layer.pl-red{color:rgb(117, 60, 255) !important}",
        ".bg-indigo, .bg-blue,#div_client_elite{background: #462f76 !important;}",
        ".input-group .form-line:after,.input-group .form-line{border:unset !important;position: unset !important;content: unset !important;}",
        ".body,.bg-custom{background: #462f76e3;color: white !important;}",
        "button.bg-indigo{background: #6028d5 !important;border-radius: 1rem !important;box-shadow: #340839 2px 2px 12px 2px !important;}",
        ".theme-deep-orange .navbar {background: #6028d5 ;}",
        ".theme-deep-orange .navbar ,.theme-red .navbar{ background-color: #472d7dc2 !important;box-shadow: unset;-webkit-box-shadow: unset;-moz-box-shadow: unset;-ms-box-shadow: unset;}",
        "table.table.table.bg-blue a, table.table.table.bg-blue a:active, table.table.table.bg-blue a:focus{   background-color: unset !important;color: white;text-decoration: none;font-weight: bolder;font-size: 1.5rem;word-break: break-word;}",
        ".sidebar .legal .copyright {word-break: break-word;text-wrap: pretty !important;color:white;}",
        ".theme-red .sidebar .legal {background-color: #000;}"
    ],
    moradoLigth: [
        "a.toggled.waves-effect, a.waves-effect.waves-block:hover, a.waves-effect.waves-block:hover > *,.spinner-layer.pl-red{color:rgb(117, 60, 255) !important}",
        ".bg-indigo, .bg-blue,#div_client_elite{background: #462f76 !important;}",
        ".input-group .form-line:after,.input-group .form-line{border:unset !important;position: unset !important;content: unset !important;}",
        ".body,.bg-custom{background: #462f76e3;color: white !important;}",
        "button.bg-indigo{background: #6028d5 !important;border-radius: 1rem !important;box-shadow: #340839 2px 2px 12px 2px !important;}",
        ".theme-deep-orange .navbar {background: #6028d5 ;}",
        ".theme-deep-orange .navbar ,.theme-red .navbar{ background-color: #472d7dc2 !important;box-shadow: unset;-webkit-box-shadow: unset;-moz-box-shadow: unset;-ms-box-shadow: unset;}",
        "table.table.table.bg-blue a, table.table.table.bg-blue a:active, table.table.table.bg-blue a:focus{   background-color: unset !important;color: white;text-decoration: none;font-weight: bolder;font-size: 1.5rem;word-break: break-word;}",
        ".sidebar .legal .copyright {word-break: break-word;text-wrap: pretty !important;color:white;}",
        ".theme-red .sidebar .legal {background-color: #000;}",
        '.table-striped>tbody>tr:nth-of-type(odd){color: black;background-color: white;font-weight: bolder;font-size: 1.5rem;}',
        '::-webkit-scrollbar{width: 9px;background: #6c33b7;}',
        '.pagination>li.active a,.pagination>li.next a,.pagination>li.previous a{background:#38024fe0!important;color:#fff!important}',
        '.pagination > li.active a,.pagination > li.previous a,.pagination > li.next a {  background: #38024fe0 !important;  color: white !important;}',
        '::-webkit-scrollbar-thumb{background: white;border-radius: 1rem;}',
    ],
    ninguno: []
}